# Generated by Django 3.1.7 on 2022-03-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20220212_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
        migrations.RenameField(
            model_name='property',
            old_name='illumination',
            new_name='illumination_health',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='ilumination',
            new_name='ilumination_energy',
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=19),
            preserve_default=False,
        ),
    ]
